plugins {
    id 'application'
}

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}

application {
    mainClass = 'topit.lwjgl3.Lwjgl3Launcher'
}

tasks.named('run') {
    // игра ищет картинки относительно папки assets
    workingDir = rootProject.file('assets')
    if (System.getProperty('os.name').toLowerCase().contains('mac')) {
        jvmArgs '-XstartOnFirstThread'
    }
}
